### PR TITLE
Update URL to bukkit Maven Repo

### PR DESCRIPTION
**Pull request by msgilligan**
I was trying to build with Maven and got this error:

[ERROR] Failed to execute goal on project GroovyBukkit: Could not resolve dependencies for project org.bukkit.plugin:GroovyBukkit:jar:0.8-SNAPSHOT: Failed to collect dependencies for [org.bukkit:bukkit:jar:1.2.4-R1.1-SNAPSHOT (compile), org.bukkit:craftbukkit:jar:1.2.4-R1.1-SNAPSHOT (compile), org.codehaus.groovy:groovy:jar:1.8.6 (compile), junit:junit:jar:4.10 (test)]: Failed to read artifact descriptor for org.bukkit:bukkit:jar:1.2.4-R1.1-SNAPSHOT: Could not transfer artifact org.bukkit:bukkit:pom:1.2.4-R1.1-SNAPSHOT from/to bukkut-repo (http://artifacts.lukegb.com/artifactory/repo): artifacts.lukegb.com: Unknown host artifacts.lukegb.com -> [Help 1]

Changing the repo URL fixed it.

### CODE REVIEW

**Comment by msgilligan** [comment]
Looks like @Aurifier has made the same change as well as bumped the versions of some of the dependencies.

**Comment by Aurifier** [comment]
Was I not supposed to do that? I just did what I needed to do so I could use the plugin and issued a request from that, but I'm really not too familiar with a)open-source collaboration or b)Maven... <sheepish grin>

**Comment by msgilligan** [comment]
No, you did good work @Aurifier .  I'm just noting that you and I have had the same problem and have made similar fixes.

**Comment by Aurifier** [comment]
Thanks! I know the author personally and I talked to him in August about GroovyBukkit, but I haven't heard anything since then.

**Pull request merged**
